export const useCases = [
  {
    id: "critical-reporting",
    title: "Un reporting dépend d’une personne ou d’un fichier fragile",
    shortTitle: "Reporting fragile",
    before: "Plusieurs sources, des copier-coller et un risque d’erreur à chaque cycle.",
    context: "Structurer les sources, périodes, versions, responsables et règles de contrôle.",
    execution: "Collecter les données, contrôler les écarts et produire le reporting.",
    intelligence:
      "Interpréter les anomalies seulement lorsque les règles déterministes ne suffisent pas.",
    humanControl: "Faire valider les exceptions et les changements sensibles.",
    outcome: "Un reporting reproductible, traçable et moins dépendant d’une seule personne.",
    examples: ["QBR partenaires", "Pack de direction", "Reporting multi-sites"],
  },
  {
    id: "decision-data",
    title: "Une donnée existe, mais n’arrive pas jusqu’à la bonne décision",
    shortTitle: "Décision sans contexte",
    before: "Les données utiles sont dispersées et chaque équipe défend sa propre version.",
    context: "Réunir les sources, définitions, responsabilités et niveaux de confiance.",
    execution: "Calculer les indicateurs et déclencher les revues ou actions prévues.",
    intelligence: "Qualifier les écarts, synthétiser la situation et préparer les options.",
    humanControl: "Laisser les arbitrages engageants aux responsables désignés.",
    outcome: "Une décision reliée à ses données, ses règles et sa prochaine action.",
    examples: ["Trésorerie", "Anomalies de coûts", "Priorisation commerciale"],
  },
  {
    id: "workflow-tools",
    title: "Un workflow traverse trop d’outils et de personnes",
    shortTitle: "Handoffs manuels",
    before: "Une demande passe par un formulaire, un email, un tableur, un CRM et des relances.",
    context: "Identifier le dossier, son statut, son responsable et la prochaine étape attendue.",
    execution: "Synchroniser les systèmes et créer automatiquement les actions déterministes.",
    intelligence: "Lire ou classer les demandes ambiguës avant de proposer une suite autorisée.",
    humanControl: "Transmettre les cas hors règle avec leur contexte complet.",
    outcome: "Un workflow visible qui avance sans perdre les exceptions.",
    examples: ["Onboarding", "Suivi de devis", "Traitement documentaire"],
  },
  {
    id: "expertise-product",
    title: "Une expertise forte reste difficile à appliquer à grande échelle",
    shortTitle: "Expertise non structurée",
    before: "La méthode dépend de quelques personnes et varie selon les outils ou les dossiers.",
    context: "Formaliser les concepts, données, règles, cas limites et responsabilités.",
    execution:
      "Transformer la méthode en parcours, calculs, contrôles et livrables reproductibles.",
    intelligence: "Aider à rechercher, interpréter ou préparer une recommandation contextualisée.",
    humanControl: "Conserver la validation de l’expert là où son jugement engage le résultat.",
    outcome: "Une expertise accessible dans un système sans être réduite à un chatbot.",
    examples: ["Diagnostic financier", "Pricing", "Contrôle métier"],
  },
  {
    id: "ai-pilot",
    title: "Un pilote IA fonctionne en démonstration, pas dans l’opération",
    shortTitle: "Pilote IA bloqué",
    before: "Le modèle sait répondre, mais les données, les droits et les actions restent flous.",
    context: "Définir les sources, l’état du dossier, les permissions et les critères de réussite.",
    execution: "Connecter le pilote aux étapes réelles et journaliser les actions.",
    intelligence: "Limiter le système à des décisions ou actions explicitement autorisées.",
    humanControl: "Définir les seuils de validation, de refus et d’escalade.",
    outcome: "Un système évaluable qui peut être industrialisé, corrigé ou arrêté sur des faits.",
    examples: ["Analyse documentaire", "Qualification", "Assistant opérations"],
  },
  {
    id: "regulated",
    title: "Une opération sensible exige davantage de contrôle",
    shortTitle: "Opération sensible",
    before: "Données confidentielles, SI fermé et responsabilités difficiles à déléguer.",
    context: "Cartographier les accès, les données nécessaires et les responsabilités de décision.",
    execution: "Automatiser uniquement les passages compatibles avec les règles de l’organisation.",
    intelligence: "Utiliser des modèles évalués sur un périmètre explicite et observable.",
    humanControl: "Prévoir validation, traçabilité, moindre privilège et reprise manuelle.",
    outcome: "Une trajectoire progressive vers plus d’autonomie sans créer de boîte noire.",
    examples: ["Finance", "Assurance", "Secteur public"],
  },
] as const;

export const illustrativeStatus = "CAS D’USAGE ILLUSTRATIF" as const;
