/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as CasUsageRouteImport } from './routes/cas-usage'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as MethodeRouteImport } from './routes/methode'
import { Route as RealisationsRouteImport } from './routes/realisations'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ServicesAgenticRouteImport } from './routes/services.agentic'
import { Route as ServicesAutomatisationRouteImport } from './routes/services.automatisation'
import { Route as ServicesCrmRouteImport } from './routes/services.crm'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const CasUsageRoute = CasUsageRouteImport.update({
  id: '/cas-usage',
  path: '/cas-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodeRoute = MethodeRouteImport.update({
  id: '/methode',
  path: '/methode',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsRoute = RealisationsRouteImport.update({
  id: '/realisations',
  path: '/realisations',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAgenticRoute = ServicesAgenticRouteImport.update({
  id: '/services/agentic',
  path: '/services/agentic',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAutomatisationRoute = ServicesAutomatisationRouteImport.update({
  id: '/services/automatisation',
  path: '/services/automatisation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCrmRoute = ServicesCrmRouteImport.update({
  id: '/services/crm',
  path: '/services/crm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/cas-usage': typeof CasUsageRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/methode': typeof MethodeRoute
  '/realisations': typeof RealisationsRoute
  '/work': typeof WorkRoute
  '/services/agentic': typeof ServicesAgenticRoute
  '/services/automatisation': typeof ServicesAutomatisationRoute
  '/services/crm': typeof ServicesCrmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/cas-usage': typeof CasUsageRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/methode': typeof MethodeRoute
  '/realisations': typeof RealisationsRoute
  '/work': typeof WorkRoute
  '/services/agentic': typeof ServicesAgenticRoute
  '/services/automatisation': typeof ServicesAutomatisationRoute
  '/services/crm': typeof ServicesCrmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/cas-usage': typeof CasUsageRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/methode': typeof MethodeRoute
  '/realisations': typeof RealisationsRoute
  '/work': typeof WorkRoute
  '/services/agentic': typeof ServicesAgenticRoute
  '/services/automatisation': typeof ServicesAutomatisationRoute
  '/services/crm': typeof ServicesCrmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/cas-usage'
    | '/confidentialite'
    | '/contact'
    | '/journal'
    | '/mentions-legales'
    | '/methode'
    | '/realisations'
    | '/work'
    | '/services/agentic'
    | '/services/automatisation'
    | '/services/crm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/cas-usage'
    | '/confidentialite'
    | '/contact'
    | '/journal'
    | '/mentions-legales'
    | '/methode'
    | '/realisations'
    | '/work'
    | '/services/agentic'
    | '/services/automatisation'
    | '/services/crm'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/cas-usage'
    | '/confidentialite'
    | '/contact'
    | '/journal'
    | '/mentions-legales'
    | '/methode'
    | '/realisations'
    | '/work'
    | '/services/agentic'
    | '/services/automatisation'
    | '/services/crm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  CasUsageRoute: typeof CasUsageRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  JournalRoute: typeof JournalRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MethodeRoute: typeof MethodeRoute
  RealisationsRoute: typeof RealisationsRoute
  WorkRoute: typeof WorkRoute
  ServicesAgenticRoute: typeof ServicesAgenticRoute
  ServicesAutomatisationRoute: typeof ServicesAutomatisationRoute
  ServicesCrmRoute: typeof ServicesCrmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cas-usage': {
      id: '/cas-usage'
      path: '/cas-usage'
      fullPath: '/cas-usage'
      preLoaderRoute: typeof CasUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methode': {
      id: '/methode'
      path: '/methode'
      fullPath: '/methode'
      preLoaderRoute: typeof MethodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations': {
      id: '/realisations'
      path: '/realisations'
      fullPath: '/realisations'
      preLoaderRoute: typeof RealisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/agentic': {
      id: '/services/agentic'
      path: '/services/agentic'
      fullPath: '/services/agentic'
      preLoaderRoute: typeof ServicesAgenticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/automatisation': {
      id: '/services/automatisation'
      path: '/services/automatisation'
      fullPath: '/services/automatisation'
      preLoaderRoute: typeof ServicesAutomatisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/crm': {
      id: '/services/crm'
      path: '/services/crm'
      fullPath: '/services/crm'
      preLoaderRoute: typeof ServicesCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  CasUsageRoute: CasUsageRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  JournalRoute: JournalRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MethodeRoute: MethodeRoute,
  RealisationsRoute: RealisationsRoute,
  WorkRoute: WorkRoute,
  ServicesAgenticRoute: ServicesAgenticRoute,
  ServicesAutomatisationRoute: ServicesAutomatisationRoute,
  ServicesCrmRoute: ServicesCrmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
